Contact list
arthur-wfb/android-project pull request #2
Opened 2020-04-25 15:42 UTC by arthur-wfb

Реализованы верстка и навигация Single Activity приложение списка контактов.
Сгенерированные цвета:
colorPrimary :#aac3db
colorAccent: #4a1d6e
![Screenshot_20200425_203707_com_ururu2909_firstapp](https://user-images.githubusercontent.com/53261456/80284038-4b072f80-8735-11ea-906d-38f1f4d55096.jpg)
![Screenshot_20200425_203712_com_ururu2909_firstapp](https://user-images.githubusercontent.com/53261456/80284041-4c385c80-8735-11ea-93e9-669e4e5cdbfa.jpg)

2020-04-25 16:01 UTC, goblinr requested changes

2020-04-25 16:01 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/Contact.java
> +    private String phoneNumber;
Если не предполагается изменение состояния объекта - используй `final` при определении полей объекта

2020-04-25 16:01 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactFragment.java
> +public class ContactFragment extends Fragment {
Этот класс нигде не используется. Нужно удалить.

2020-04-25 16:01 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +    static Contact[] contacts = {
`static final Contact[]`

2020-04-25 16:01 UTC, goblinr commented on app/src/main/res/layout/fragment_contact.xml
> +        android:layout_height="37dp"
Жесткие размеры - не поворотливы. Нужно стремиться к "резиновому" поведению верстки. Т.е. использовать `match_parent` либо `wrap_content`
Это касается и всех остальных разметок в твоем проекте

2020-04-25 16:01 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView5"
Старайся избегать таких названий id. Это приведет к не читаемости в коде, который будет использовать эти вьюшки. Это касается и всех остальных разметок в проекте.

2020-04-29 05:58 UTC, goblinr requested changes

2020-04-29 05:58 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        getActivity().setTitle("Список контактов");
Это не верно. Фрагмент с деталями контакта может в будущем запускаться не обязательно с экрана списка контактов

2020-04-29 05:58 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_height="27dp"
Нечетные размеры. Следует от них избавляться

2020-04-29 05:58 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_height="27dp"
Нечетные размеры

2020-04-29 05:58 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_height="27dp"
Нечетные размеры

2020-04-29 07:50 UTC, arthur-wfb commented
Не понимаю как решить эту проблему правильно. Метод onResume() не вызывается и я не могу изменить текст тулбара.

2020-04-29 07:51 UTC, goblinr requested changes

2020-04-29 07:51 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    getActivity().setTitle("Список контактов");
Это слишком сложно. Из пушки по воробьям.
Пересмотри лекцию про жизненный цикл фрагмента.
Когда мы возвращаемся в этот фрагмент по бэкстеку - у него обязательно вызовется метод жизненного цикла `onStart()` - просто установи текст в тулбаре в нем.

2020-04-29 07:58 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    getActivity().setTitle("Список контактов");
У меня он почему-то не вызывается.

2020-04-29 08:12 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    getActivity().setTitle("Список контактов");
Это потому что ты в транзакции используешь `add`, т.е. фрагмент списка контактов - остается жить. Нужно использовать `replace`

2020-04-29 08:17 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    getActivity().setTitle("Список контактов");
Все равно не вызывается. Это может быть связано с тем, что я заменяю фрагмент не динамически добавленный, а прописанный в XML?

2020-04-29 08:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    getActivity().setTitle("Список контактов");
да, именно из-за этого.

2020-04-29 08:33 UTC, goblinr requested changes

2020-04-29 08:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/MainActivity.java
> +        ft.commit();
При повороте экрана - фрагмент добавится еще раз.
нужно обезопаситься от этого таким образом:
```java
if (savedInstanceState == null) {
  // делаем транзакцию т.к. мы точно запускаемся впервые
}
```

2020-04-29 08:36 UTC, goblinr approved these changes

2020-04-29 08:44 UTC, merged