Добавил привязанный сервис для получения данных
arthur-wfb/android-project pull request #3
Opened 2020-05-06 08:15 UTC by arthur-wfb

Добавил привязанный сервис, который имеет публичное API предоставляющее список контактов и отдельного контакта.

2020-05-06 09:33 UTC, goblinr requested changes

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +    private ContactDetailsFragment(ContactsService mService){
Так делать нельзя. Система , при восстановлении фрагмента, будет использовать конструктор **без** параметров, которого теперь нет - что приведет к крэшу приложения. Пересмотри 2-ю лекцию о том как должны взаимодействовать активность и фрагмент

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        contactPhoneNumber.setText(mService.getContact(index).getPhoneNumber());
В домашнем задании было требование - получать контакт на отдельном потоке, т.е. асинхронно.

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +    ContactListFragment(ContactsService mService){
См. комментарий выше

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +        final Contact[] contacts = mService.getContacts();
тоже самое

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsService.java
> +        return Contact.contacts[id];
Чиение контактов нужно реализовать на отдельном потоке

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/MainActivity.java
> +                    bindService(intent, mConnection, Context.BIND_AUTO_CREATE);
Мне не понятно, зачем делать это на отдельном потоке?

2020-05-06 09:33 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/MainActivity.java
> +        unbindService(mConnection);
Если `bindService` происходит в `onCreate` - то `unbindService` нужно делать в `onDestroy`

2020-05-06 15:31 UTC, goblinr requested changes

2020-05-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        } catch (ExecutionException | InterruptedException | NullPointerException e){
Здесь происходит блокирование главного потока программы. Суть асинхронного взаимодействия - в том что бы не блокировать поток в котором у нас отрисовывается пользовательский интерфейс, что бы повысить отзывчивость программы. В будущем, мы будем читать контакты из БД, а это не очень быстрая операция, которая может привести к подлагиваниям интерфейса.

2020-05-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +        } catch (ExecutionException | InterruptedException | NullPointerException e){
Здесь тоже самое

2020-05-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +    public interface CanGetService {
Этот интерфейс следует вынести из `ContactListFragment`

2020-05-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsService.java
> +        return future.get();
Как я писал выше - это приводит к блокированию потока, на котором мы вызываем метод `getContacts`

2020-05-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsService.java
> +        return future.get();
И здесь тоже самое

2020-05-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/MainActivity.java
> +            bindService(intent, mConnection, Context.BIND_AUTO_CREATE);
Это не верно. `bindService` мы хотим выполнять в любом случае, даже если мы восстанавливаемся после пересоздания активности. А вот фрагмент добавлять, мы хотим только когда стартуем впервые.

2020-05-08 14:53 UTC, goblinr requested changes

2020-05-08 14:53 UTC, goblinr commented on app/src/main/AndroidManifest.xml
> +        </service>
`<service android:name=".ContactsService" />`

2020-05-08 14:53 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        contactPhoneNumber = null;
Их нужно обнулять в `onDestroyView`

2020-05-08 14:53 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +            });
Зачем 2 разных `post`? Какой в этом смысл?
```java
contactName.post(new Runnable() {
                @Override
                public void run() {
                    contactName.setText(contact.getName());
                    contactPhoneNumber.setText(contact.getPhoneNumber());
                }
            });
```

2020-05-08 14:53 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    });
Здесь `post` - не нужны

2020-05-08 14:53 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +            setListAdapter(contactAdapter);
А вот здесь уже нужен `post`

2020-05-08 14:53 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/MainActivity.java
> +        }
`createdFirstTime  = savedInstanceState == null`

2020-05-08 16:43 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +            setListAdapter(contactAdapter);
```
final ListView listView = getListView();
listView.post(new Runnable() {
    @Override
    public void run() {
        listView.setAdapter(contactAdapter);
    }
});
```
Таким образом? 

У меня исключение ```java.lang.IllegalStateException: Content view not yet created```

2020-05-09 14:07 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +            setListAdapter(contactAdapter);
тебе в принципе, нужно создавать весь адаптер на главном потоке программы

2020-05-09 15:09 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +            setListAdapter(contactAdapter);
Но как тогда передать массив контактов в адаптер, если доступ к этому массиву у меня есть только в методе onComplete?

2020-05-09 15:30 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +            setListAdapter(contactAdapter);
```java
public void onComplete(final Contact[] result) {
  View view = getView();
  if (view != null) {
    view.post(new Runnable() {
            @Override
             public void run() {
                ArrayAdapter<Contact> contactAdapter = new ArrayAdapter<Contact>(getActivity(), 0, contacts) {...}
                setListAdapter(contactAdapter);
             }
     });
  }
}
```

2020-05-09 16:58 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +            setListAdapter(contactAdapter);
Понял, спасибо

2020-05-10 03:57 UTC, goblinr requested changes

2020-05-10 03:57 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +                    contactPhoneNumber.setText(contact.getPhoneNumber());
Прежде чем трогать вьюшки, следует проверить их на null

2020-05-10 03:57 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +    private View view;
ссылку на view нужно обнулять в `onDestroyView` если ты решил держать на нее жесткую ссылку в фрагменте.

2020-05-10 03:57 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/MainActivity.java
> +    Object createdFirstTime;
Лучше заведи булевый флаг

2020-05-10 12:39 UTC, goblinr requested changes

2020-05-10 12:39 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +                        contactPhoneNumber.setText(contact.getPhoneNumber());
Здесь тоже нужно проверить на `null` т.к. к тому времени, как EventLooper обработает этот `post` - вьюшка фрагмента может быть уже уничтожена

2020-05-10 12:57 UTC, goblinr approved these changes

2020-05-10 12:58 UTC, merged