Рефакторинг существующего кода приложения с использованием MVVM
arthur-wfb/android-project pull request #6
Opened 2020-05-31 11:14 UTC by arthur-wfb

Вынес всю работу сервиса в репозиторий
Удалил сервис загрузки контактов.
Сделал рефакторинг кода с использованием паттерна MVVM

2020-05-31 16:26 UTC, goblinr requested changes

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        ContactsViewModel model = new ViewModelProvider(requireActivity()).get(ContactsViewModel.class);
Получать ссылку на view model лучше всего в `onCreate()`  фрагмента.

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +        ContactsViewModel model = new ViewModelProvider(requireActivity()).get(ContactsViewModel.class);
Получать ссылку на view model лучше всего в `onCreate()`  фрагмента.

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        model.getContact(id).observe(getViewLifecycleOwner(), new Observer<Contact>() {
Подписку на `LiveData`  следует тоже сделать в  `onCreate()`  фрагмента. `getViewLifecycleOwner()` гарантирует, что данные будут получены в промежуток, когда вьюшка точно жива.

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +        model.getContactList().observe(getViewLifecycleOwner(), new Observer<ArrayList<Contact>>() {
Подписку на `LiveData`  следует тоже сделать в  `onCreate()`  фрагмента. `getViewLifecycleOwner()` гарантирует, что данные будут получены в промежуток, когда вьюшка точно жива.

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +                    contactName.post(new Runnable() {
Этого делать теперь не нужно. `LiveData.postValue()` гарантирует, что данные будут доставлены подписчикам на главном потоке программы

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactListFragment.java
> +                    view.post(new Runnable() {
Этого делать теперь не нужно. `LiveData.postValue()` гарантирует, что данные будут доставлены подписчикам на главном потоке программы

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/viewmodel/ContactsViewModel.java
> +                Repository repository = new Repository(context.getContentResolver());
Каждый раз создавать репозиторий - избыточно. Достаточно  один раз создать его в конструкторе ViewModel.

2020-05-31 16:26 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/viewmodel/ContactsViewModel.java
> +                Repository repository = new Repository(context.getContentResolver());
Каждый раз создавать репозиторий - избыточно. Достаточно  один раз создать его в конструкторе ViewModel.

2020-05-31 17:38 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        model.getContact(id).observe(getViewLifecycleOwner(), new Observer<Contact>() {
У меня приложение вылетает если подписываться в onCreate()

`java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()`

`java.lang.IllegalArgumentException: the bind value at index 1 is null`

2020-05-31 17:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactDetailsFragment.java
> +        model.getContact(id).observe(getViewLifecycleOwner(), new Observer<Contact>() {
Сорян, да, нужно подписываться после `onCreateView()`

2020-05-31 20:30 UTC, goblinr requested changes

2020-05-31 20:30 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/viewmodel/ContactsViewModel.java
> +        loadContact(id);
Каждый раз при вызове `getContact` создается новый `MutableLiveData`

2020-06-01 07:04 UTC, goblinr approved these changes

2020-06-01 07:07 UTC, merged