Recycler view
arthur-wfb/android-project pull request #7
Opened 2020-06-02 16:11 UTC by arthur-wfb

Добавил поиск по именам с помощью SearchView
Сделал отслеживание изменений через DIffUtils
Добавил разделитель с помощью DividerItemDecorator

Есть баг, который я не понял как исправить: если после поиска стереть текст в поисковой строке, имя первого контакта отображается не правильно. Но при отображении деталей этого контакта имя и все данные верные.

2020-06-02 17:18 UTC, goblinr requested changes

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsFragment.java
> +        getActivity().setTitle("Список контактов");
Захардкоженная строка

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsFragment.java
> +                recyclerView.setAdapter(adapter);
Это очень неправильно - каждый раз заново создавать адаптер. Такое каждый раз приводит к тому что текущий скролл перескакивает в начало списка - что будет бесить пользователя.
Адаптер следует создать один раз в `onCreateView`
Данные обновлять с помощью DiffUtils

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsFragment.java
> +        model = null;
ViewModel обнулять не нужно

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsFragment.java
> +                adapter.getFilter().filter(newText);
Это нормально, когда у тебя в адаптере 50 - 100 контактов, что будет если их будет миллион? А если миллиард?
Используй фильтрацию на уровне SQL запроса к поставщику контактов.

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +            onContactListener.onContactClick(contacts.get(getAdapterPosition()).getId());
`getAdapterPosition` необходимо проверять на `RecyclerView.NO_POSITION` прежде чем  использовать

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +public class CustomAdapter extends RecyclerView.Adapter<CustomAdapter.ContactViewHolder> implements Filterable {
`Filterable` - не нужен

2020-06-02 17:18 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +            DiffUtil.DiffResult contactDiffResult = DiffUtil.calculateDiff(contactDiffUtilCallback);
Пусть `DiffUtil` работает довольно быстро, но все же в данном случае за `O(n²)`.
Для более плавной работы адаптера, лучше делать это на отдельном потоке. Есть уже готовая реализация `ListAdapter` - можешь посмотреть на нее, там уже все это учтено.

2020-06-03 15:43 UTC, goblinr requested changes

2020-06-03 15:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/ContactsFragment.java
> +                recyclerView.setAdapter(adapter);
`setAdapter` нужно сделать 1 раз в `onCreateView`, а не каждый раз при изменении данных

2020-06-03 15:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +    private ArrayList<Contact> contacts;
Хранить список самому не нужно. `ListAdapter` это уже делает за тебя

2020-06-03 15:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +        holder.bind(contacts.get(position));
неверно. нужно использовать `getItem()`

2020-06-03 15:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +    public class ContactViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
Не используй внутренний класс для view holder'а, это приведет к невозможности в будущем сменить адаптер без потери позиции скролла, т.к. внутренний класс имеет ссылку на внешний класс.

2020-06-03 15:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/repository/Repository.java
> +    public ArrayList<Contact> getContactsByMatchOfName(String charSequence){
Этот метод почти один в один дублирует `getContacts`. Нужен рефакторинг

2020-06-03 15:43 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/viewmodel/ContactsViewModel.java
> +                contactList.postValue(repository.getContactsByMatchOfName("%"+charSequence+"%"));
Лучше пусть репозиторий подставляет `%`. Иначе получается, что ViewModel  знает о специфичных для SQL вещах

2020-06-06 15:11 UTC, arthur-wfb commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +    public class ContactViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
Я не знаю как и где в таком случае реализовать метод onClick.
Потому что когда ViewHolder был внутренним классом адаптера, у него был доступ к списку контактов которые сейчас находятся на экране, а сейчас нет.
В примерах из интернета используют внутренний класс.

2020-06-06 15:31 UTC, goblinr commented on app/src/main/java/com/ururu2909/firstapp/CustomAdapter.java
> +    public class ContactViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
Лучше воспользоваться вложенным классом и передавать ссылку на необходимые данные в конструктор ViewHolder'а. Можно даже передать ссылку на адаптер, тогда будет возможность хранить его внутри по слабой ссылке. При текущей реализации у тебя нет возможности управлять этим.

2020-06-06 16:08 UTC, goblinr approved these changes

2020-06-06 16:27 UTC, merged